name: fun_heart_eat
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  # flutter_better_camera:
  path_provider: ^1.6.27
  fluttertoast: 7.1.1
  date_format: ^1.0.9
  url_launcher: ^5.7.10
  url_launcher_web: ^0.1.0
  csv: ^4.1.0
  ftpclient: ^0.8.0
  imei_plugin: ^1.2.0
  sqflite: ^1.3.0
  path: ^1.6.2
  flutter_ringtone_player: ^2.0.0
  permission_handler: ^5.0.1+1
  auto_size_text: ^2.1.0
  vibration: ^1.7.3
  shared_preferences: ^0.5.12
  flutter_share: ^1.0.5
  lamp:
  wakelock: ^0.2.1+1
  manual_camera: ^0.0.3 
  camera: 0.8.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.4.1
  image: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/train/
  fonts:
    - family: openhuninn
      fonts:
        - asset: fonts/jf-openhuninn-1.1.ttf


